/**
 * Derived analytics loader for uc_ai_derived.json (v0.1.0).
 *
 * Server-only. Mirrors the readFileSync pattern in lib/baseline.ts so the
 * derived JSON is read once at build time. The file is regenerated by
 * data/compute_derived.py on every baseline bump — never hand-edit it.
 *
 * Three signals are exposed:
 *   - Maturity: per (entity, dimension), score 0-4 with basis
 *   - RAI concordance: per (entity, principle), status verbatim/adapted/absent
 *   - Timeline: dated events extracted from notes, sorted ascending
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { DimensionId, EntityType } from "./baseline";
import { DIMENSION_IDS, listEntities } from "./baseline";

export type MaturityBasis =
  | "dimension_populated"
  | "evidenced_true_with_source"
  | "named_leader_or_council"
  | "dated_artifact";

export type MaturityRow = {
  entity_id: string;
  dimension: DimensionId;
  score: 0 | 1 | 2 | 3 | 4;
  basis: MaturityBasis[];
};

export type RaiPrincipleId =
  | "appropriateness"
  | "transparency"
  | "accuracy_reliability_safety"
  | "fairness_nondiscrimination"
  | "privacy_security"
  | "human_values"
  | "shared_benefit"
  | "accountability";

export type RaiStatus = "verbatim" | "adapted" | "absent";

export type RaiConcordanceRow = {
  entity_id: string;
  principle_id: RaiPrincipleId;
  principle_name: string;
  status: RaiStatus;
  evidence: string | null;
};

export type TimelineRow = {
  entity_id: string;
  dimension: DimensionId;
  field: string;
  verb: string;
  date: string;
  source_id: string | null;
  snippet: string;
};

type RawDerived = {
  metadata: {
    computed_at: string;
    baseline_version: string;
    derived_version: string;
    notes: string;
  };
  maturity: MaturityRow[];
  rai_concordance: RaiConcordanceRow[];
  timeline: TimelineRow[];
};

const raw = JSON.parse(
  readFileSync(join(process.cwd(), "data", "uc_ai_derived.json"), "utf-8"),
) as RawDerived;

export const derivedMetadata = raw.metadata;

export function getMaturity(entityId: string): MaturityRow[] {
  return raw.maturity.filter((r) => r.entity_id === entityId);
}

export function getMaturityFor(
  entityId: string,
  dimension: DimensionId,
): MaturityRow | undefined {
  return raw.maturity.find(
    (r) => r.entity_id === entityId && r.dimension === dimension,
  );
}

export function getRaiConcordance(entityId: string): RaiConcordanceRow[] {
  return raw.rai_concordance.filter((r) => r.entity_id === entityId);
}

export function getTimeline(): TimelineRow[] {
  return raw.timeline;
}

export function getTimelineFor(entityId: string): TimelineRow[] {
  return raw.timeline.filter((r) => r.entity_id === entityId);
}

/**
 * Comparison-matrix-shaped view: rows = entity, cols = dimension, cell = score.
 * Use this in the Step 4 comparison page; for now it's available for chat
 * tool calls and ad-hoc queries.
 */
export type ComparisonMatrix = {
  entities: Array<{
    entity_id: string;
    entity_name: string;
    entity_type: EntityType;
    scores: Record<DimensionId, number>;
    total: number;
  }>;
  dimensions: readonly DimensionId[];
};

export function comparisonMatrix(): ComparisonMatrix {
  const rows = listEntities().map((e) => {
    const scores = {} as Record<DimensionId, number>;
    let total = 0;
    for (const dim of DIMENSION_IDS) {
      const m = getMaturityFor(e.entity_id, dim);
      const s = m?.score ?? 0;
      scores[dim] = s;
      total += s;
    }
    return {
      entity_id: e.entity_id,
      entity_name: e.entity_name,
      entity_type: e.entity_type,
      scores,
      total,
    };
  });
  return { entities: rows, dimensions: DIMENSION_IDS };
}
